# Generated by Django 3.1.3 on 2020-12-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='root',
            field=models.BooleanField(default=False),
        ),
    ]
