# Generated by Django 3.1.3 on 2020-12-01 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websockets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='ChannelRoom',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='room',
            new_name='channel_room',
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('channel_room', 'channel_name')},
        ),
    ]
