# Generated by Django 3.1.3 on 2020-12-01 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
        ('websockets', '0002_auto_20201201_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelroom',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rest.room'),
        ),
    ]
