# Generated by Django 3.1.3 on 2020-12-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websockets', '0003_channelroom_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='x',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='participant',
            name='y',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=16),
        ),
    ]
